name: Snyk Open Source Library Scan (SARIF)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
  workflow_dispatch:

jobs:
  snyk-library-scan:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Snyk CLI
        uses: snyk/actions/setup@v3

      - name: Run Snyk Dependency Scan and Generate SARIF
        env:
          SNYK_TOKEN: c80a2012-bb87-4482-beb5-399c664f183d
        run: |
          snyk test \
            --all-projects \
            --severity-threshold=medium \
            --sarif-file-output=snyk-library.sarif || true

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-library.sarif

      - name: Snyk Monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk monitor --all-projects
