name: Snyk Library Scan (SCA)

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  snyk-library-scan:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: c80a2012-bb87-4482-beb5-399c664f183d
        run: snyk auth "$SNYK_TOKEN"

      - name: Run Snyk Dependency Scan (SARIF)
        env:
          SNYK_TOKEN: c80a2012-bb87-4482-beb5-399c664f183d
        run: |
          snyk test --all-projects \
          --sarif-file-output=snyk.sarif || true

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
